### ISSUE TITLE
Problem of retrieving a saved model of natural variation

### ISSUE THREAD

**Issue by themanchangechina** [arobey1/mbrdl#1]
Excuse me, I download a pre-trained models of natural variation(**svhn-brightness.pt**) from your library, it is a .pt file. 
I want to know how to write the command `G = MUNITModelOfNatVar(args.model_path, reverse=False).cuda()` to get the model? 
I see `G = MUNITModelOfNatVar(fname, reverse=reverse, args=args).cuda()` in the load.py, how should I add the args?

**Comment by arobey1** [comment]
See commit f49bd05

You can now use 
```python
G = MUNITModelOfNatVar(fname, reverse=reverse, config=config)
```
where `config` is a path pointing to the `.yaml` configuration file for MUNIT.  The relevant file for `svhn-brightness.pt` should be `./core/models/munit/munit.yaml`

**Comment by themanchangechina** [comment]
OK, thanks~
